# Project information
site_name: 'Stephen Ra'
site_description: 'Personal website of Stephen Ra'
site_author: 'Stephen Ra'
site_url: 'https://www.stephenra.com'

# Copyright
copyright: 'Copyright &copy; 2019 Stephen Ra'

# Repository
repo_name: 'stephenra/stephenra.github.io'
repo_url: 'https://github.com/stephenra/stephenra.github.io'

# Theme
docs_dir: docs
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Lato'
    code: 'Ubuntu Mono'
  favicon: 'img/favicon.png'
  feature:
    tabs: true
  logo: 'img/logo.png'

# Site
nav:
- Latest: index.md
- Blog:
  - 2019:
    - 'On conditioning by adaptive sampling': 05-07-19-adaptive-sampling.md
    - 'Revisiting normalizing flows': 03-26-19-revisiting-flows.md
- Projects:
  - 'End-to-end learning for phenotypic discovery'
  - 'De novo molecule generation': de-novo.md
  - 'Probabilistic models for transcriptomics': transcriptomics.md
  - 'DNA-encoded libraries (DELs)': dels.md
  - 'Optimizing antibody properties': ab.md
  - 'Predicting reaction outcomes': reaction.md
- About: 
    - 'Mission': about.md
    - 'Team': team.md
    - 'Publications': publications.md
    - 'Code': code.md
    - 'Collaborators': collaborators.md

# Build directories

site_dir: 'site'


# Extras
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/stephenra'
    - type: 'twitter'
      link: 'https://twitter.com/stephenrra'

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js
  - js/mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - mdx_math
  - toc:
      permalink: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
