# Project information
site_name: 'Stephen Ra'
site_description: 'Personal website of Stephen Ra'
site_author: 'Stephen Ra'
site_url: 'https://www.stephenra.com'

# Copyright
copyright: 'Copyright &copy; 2022 Stephen Ra'

# Theme
docs_dir: docs
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Lato'
    code: 'Ubuntu Mono'
  favicon: 'img/favicon.png'
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
  logo: 'img/logo.png'

# Site
nav:
- About: 'index.md'
- Blog:
  - blog/index.md


# Build directories
# site_dir: 

# Extras
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/solid/envelope-open'
      link: 'mailto:contact@stephenra.com'
    - icon: 'fontawesome/solid/graduation-cap'
      link: 'https://scholar.google.com/citations?user=bxl__-MAAAAJ&hl=en'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/stephenra'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/stephenrra'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/stephenra/'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - mdx_math
  - meta
  - toc:
      permalink: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde   # Hide table of contents

#Plugins
plugins:
  - blog
  - bibtex:
      bib_file: "docs/bib/refs.bib"
      cite_style: "pandoc"